server:
  port: 8769

eureka:
  instance:
    hostname: peer2
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8769/eureka/

spring:
  application:
    name: eureka-server
  profiles: peer2